### PR TITLE
fix: correct sorting conversations by updated date

### LINKED ISSUE #89: [AI Chat] The shared chat is not displayed at the top of the list
### Library name and version

0.1.0

### What steps will reproduce the bug?

Open the link with the shared chat

### What is the expected behavior?

The chat is added at the top of the list of shared chats

### What do you see instead?

The chat is added in a random order, sometimes at the bottom of the list of shared chats

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jane-taleika**
### Applicable issues

- fixes #89 

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

### CODE REVIEW

File: libs/conversation-list/src/utils/conversations-grouping.ts [hunk 1]
```diff
@@ -29,6 +29,9 @@ const getDayDifference = (currentDate: Date, updatedDate: Date) => {
   return Math.floor(diff / (1000 * 60 * 60 * 24));
 };
 
+const getUpdatedAtTime = (conversation: ConversationInfo): number | null =>
+  conversation?.updatedAt || Number(conversation?.id?.split('-').pop());
```
Comment (likeamike) [inline libs/conversation-list/src/utils/conversations-grouping.ts]: why do we use '?' on conversation when it’s guaranteed by the interface?

**Review by MargoGrodno-epam — DISMISSED** [review]

**Review by likeamike — APPROVED** [review]

**Review by MargoGrodno-epam — APPROVED** [review]
