### PR TITLE
fix: support constrains parsing for sdmx with dial mode

### LINKED ISSUE #188: [AI Chat][Cross-dataset query] Not valid facet items list is displayed in filters
### StatGPT Global Trusted Data Commons version

0.1.0

### What steps will reproduce the bug?

1. Go to Welcome page
2. Send some request to get data with grid attachment
3. Go to advanced view
4. Go to filters 
5. Go to some facet e.g. 'Frequency'

### What is the expected behavior?

Should display valid facet items list

### What do you see instead?

Not valid facet items list is displayed in filters

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MargoGrodno-epam**
### Applicable issues

- fixes https://github.com/epam/statgpt-global-trusted-data-commons/issues/188

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

### CODE REVIEW

File: libs/sdmx-toolkit/src/api/sdmx-config.ts [hunk 1]
```diff
@@ -5,5 +5,6 @@ export interface SdmxApiConfig {
   jwt?: string;
   apiKey?: string;
   useDialAuth?: boolean;
```
Comment (jane-taleika) [inline libs/sdmx-toolkit/src/api/sdmx-config.ts]: Look's like it's not used anywhere else

Comment (MargoGrodno-epam) [reply libs/sdmx-toolkit/src/api/sdmx-config.ts]: removed

**Review by jane-taleika — APPROVED** [review]
