### PR TITLE
fix: support time period facet behaviour for datasets without time period constraints

### LINKED ISSUE #175: [AI chat][Cross-dataset query] Custom time period is not work for BIS datasets
### StatGPT Global Trusted Data Commons version

0.1.0

### What steps will reproduce the bug?

1. Go to Welcome page
2. Send request to get data from BIS dataset 
3. Go to advanced view
4. Go to filters
5. Click on Time period
6. Select custom

### What is the expected behavior?

Custom time period should work

### What do you see instead?

Custom time period is not work for BIS datasets

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jane-taleika**
### Applicable issues

- fixes [ #175 ](https://github.com/epam/statgpt-global-trusted-data-commons/issues/175)

### Checklist

- [ ] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

### CODE REVIEW

**Comment by likeamike** [comment]
Is that correct link at the description?
image

**Comment by likeamike** [comment]
please run format and lint on this

File: libs/conversation-view/src/utils/attachments/time-period.ts [hunk 1]
```diff
@@ -201,3 +210,26 @@ export const getMergedInitialConstraints = (
 
   return mergedTimeRange;
 };
+
+  // workaround for specific case for datasets without time period constraints
+export const getTimeRangeFromDataQueries = (
```
Comment (likeamike) [inline libs/conversation-view/src/utils/attachments/time-period.ts:215]: please cover this function with tests

Comment (likeamike) [inline libs/conversation-view/src/utils/attachments/time-period.ts:215]: In multi-dataset mode the fallback stops at the first dataset with a time period, ignoring the rest. Could you verify this works correctly when multiple datasets have different time period ranges?

Comment (jane-taleika) [reply libs/conversation-view/src/utils/attachments/time-period.ts:215]: If at least one dataset has constraints or selected time range - everything would work as it should ( it was covered and tested in previous issues)
this is fallback specifically for the cases where both constraints and selected time range are nonexistent (dataset without constraints + clearAllFilters action was called). I added code to cover cases where more than one dataset has no constraints.

**Review by likeamike — APPROVED** [review]
